### ISSUE TITLE
New Hoichoi layout is not working

### ISSUE THREAD

**Issue by hemlok89** [tzsk/hoichoi#1]
Hello, recently Hoichoi changed how videos are accessed. Without subscription, there is no way to access the video. Is there any way to bypass this with this script?

**Comment by tzsk** [comment]
Hey, @hemlok89  cracking the new website was tough 😥. 

Took a little time, but finally figured it out 😎 💪. But due to tight security, only the Tampermonkey option works for `v2.0` 😞. Chrome and Firefox extensions will come soon (maybe 🙊)

#### Tampermonkey

1. Install `Tampermonkey` extension from http://tampermonkey.net.
2. Click on `Tampermonkey` icon and enable it if it is not already enabled.
3. Click here to install the script: [Hoichoi](https://github.com/tzsk/hoichoi/raw/master/Hoichoi.user.js)

**Give this package a star ⭐️ if you like it**

**Comment by tzsk** [comment]
# 🔥 Android App Released 🔥 

## Download the APK from here: [Hoichoi TV](https://drive.google.com/file/d/1G0bnJCjKZt3IcyEUxQHIEMq9zct0LldX/view?usp=drivesdk)

### Don't forget to report any issues. 🥇

**Comment by hemlok89** [comment]
Hey man, the app is working great. Streams directly to my video player. Awesome work.
