### ISSUE TITLE
hoichoi downloader is not working

### ISSUE THREAD

**Issue by annoynomous123** [tzsk/hoichoi#2]
hoichoi is recreated their site and change the options help

**Comment by tzsk** [comment]
Hey, @annoynomous123 cracking the new website was tough 😥. 

Took a little time, but finally figured it out 😎 💪. But due to tight security, only the Tampermonkey option works for `v2.0` 😞. Chrome and Firefox extensions will come soon (maybe 🙊)

#### Tampermonkey

1. Install `Tampermonkey` extension from http://tampermonkey.net.
2. Click on `Tampermonkey` icon and enable it if it is not already enabled.
3. Click here to install the script: [Hoichoi](https://github.com/tzsk/hoichoi/raw/master/Hoichoi.user.js)

**Give this package a star ⭐️ if you like it**

**Comment by tzsk** [comment]
# 🔥 Android App Released 🔥 

## Download the APK from here: [Hoichoi TV](https://drive.google.com/file/d/1G0bnJCjKZt3IcyEUxQHIEMq9zct0LldX/view?usp=drivesdk)

### Don't forget to report any issues. 🥇

**Comment by Mainak009** [comment]
PC downloader link not working please update
